src/models/User.py
from main import db
from flask_login import UserMixin
# from models.Bookings import Bookings
# from sqlalchemy.orm import backref
from datetime import datetime


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    created_at = db.Column(db.DateTime, default=datetime.now)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(1000))
    membership = db.Column(db.String(1000))
    valid = db.Column(db.String(1000))
    valid_till = db.Column(db.String(1000))
    is_admin = db.Column(db.Boolean())

    bookings = db.relationship("Bookings", backref="user", lazy="dynamic")

src/controllers/auth.py
# Import Database
from main import db

# Import flask and its requirements
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from flask_login import current_user

# secure password with sha256 in database
from werkzeug.security import generate_password_hash, check_password_hash

# import created forms
from forms.forms import RegistrationForm

# import models
from models.User import User


auth = Blueprint('auth', __name__)


# Signup Route
@auth.route('/signup')
def signup():
    return render_template('signup.html')


# Sign up route
@auth.route('/signup', methods=['POST'])
def signup_post():
    try:
        form = RegistrationForm()
        if form.validate():
            email = request.form.get('email')
            name = request.form.get('name')
            password = request.form.get('password')
            new_user = User(email=email, name=name,
                            password=generate_password_hash(
                                password, method='sha256'),
                            valid=False, membership="None",
                            valid_till="None",
                            is_admin=False)
            db.session.add(new_user)
            db.session.commit()
            flash('Please Log in below')
            return redirect(url_for('main.profile'))
    except Exception:
        flash('Email already registered')
        render_template('signup.html', form=form, error=form.errors)

    return render_template('signup.html', form=form, error=form.errors)


# Show Log in page
@auth.route('/login')
def login():
    return render_template('login.html')


# Login Route
@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


# User Password Change Route from within account on profile page
@auth.route('/profile', methods=["POST"])
@login_required
def user_password_change():
    user_id = current_user._get_current_object()
    password = request.form.get('password')
    if len(password) < 6:
        flash('Password not valid')
        return redirect(url_for('main.profile'))
    else:
        user_id.password = generate_password_hash(password, method='sha256')
        db.session.commit()
        flash('Password changed')

    return redirect(url_for('main.profile'))


# Logout Route
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

src/controllers/main.py
# Import the database
from main import db

# Import flask and its dependencies
from flask_login import login_required, current_user
from flask import Blueprint, request, render_template

# import models
from models.Bookings import Bookings
from models.User import User

main = Blueprint('main', __name__)


# Nav Bar Routes


# Shows the Index page
@main.route('/')
def index():
    return render_template('index.html')


# Shows the How to play page
@main.route('/play')
def play():
    return render_template("play.html")


# Shows the Calender overview page
@main.route('/calendar')
def calendar():
    return render_template("calendar.html")


# Shows the memberships page
@main.route('/memberships')
def memberships():
    return render_template("memberships.html")


# Shows the contuct us page
@main.route('/contact')
def contact():
    return render_template("contact.html")


# Shows the about us page
@main.route('/about')
def about():
    return render_template("about.html")


# Shows the default date calender select page
@main.route('/date')
def date():
    return render_template('date.html')


# Shows the lessons page under book a session drop down once logged in
@main.route('/lessons', methods=["GET"])
@login_required
def get_lessons():

    lessons = Bookings.query.filter((Bookings.booking_type) == "Lesson").all()
    return render_template('lessons.html', lessons=lessons)


# Shows the account page once logged in
@main.route('/profile')
@login_required
def profile():
    user_id = current_user._get_current_object()
    sessions = Bookings.query.filter_by(user_id=user_id.id).order_by(
                                        Bookings.date.desc()).all()
    lessons = Bookings.query.filter((Bookings.booking_type) == "Lesson").all()

    return render_template('profile.html', sessions=sessions, lessons=lessons)

# Admin Routes

# FOR ADMIN LOG IN ONLY - under the admin buttton selecting users will
# query all users and present them on the users page


@main.route('/users/query', methods=['GET'])
@login_required
def query_users():
    try:
        if current_user.is_admin is True:
            users = User.query.all()
            return render_template('users.html', users=users)
        else:
            return render_template('index.html')
    except (Exception):
        return render_template('index.html')


# FOR ADMIN LOG IN ONLY - under the admin buttton selecting users
# will query a single user and present them on the user edit page


@main.route('/users/query/<int:user_id>', methods=["GET"])
@login_required
def get_single_users(user_id):
    try:
        if current_user.is_admin is True:
            users = User.query.filter_by(id=user_id).one()
            return render_template('user_edit.html', users=users)
        else:
            return render_template('index.html')
    except (Exception):
        return render_template('index.html')


# FOR ADMIN LOG IN ONLY - under the admin buttton selecting users
# will update the details of the selected user and return the user edit page


@main.route('/users/query/<int:user_id>/update', methods=["POST"])
@login_required
def edit_single_users(user_id):
    try:
        if current_user.is_admin is True:
            update_user = User.query.filter_by(id=user_id).first()
            update_user.email = request.form.get("email")
            update_user.name = request.form.get("name")
            update_user.membership = request.form.get("membership")
            update_user.valid_till = request.form.get("valid_till")
            update_user.valid = request.form.get("valid")

            db.session.commit()
            return render_template('user_edit.html', users=update_user)
        else:
            return render_template('index.html')
    except (Exception):
        return render_template('index.html')


# FOR ADMIN LOG IN ONLY - under the admin buttton selecting create lessons
# will render the booking a lesson for others to book

# Lessons can also be created by selecting a date under book a lesson and
# assigning it as a lesson

@main.route('/lessons/create/<int:booking_id>', methods=["GET", "POST"])
@login_required
def create_lessons(booking_id):
    user = current_user._get_current_object()
    update_booking = Bookings()
    update_booking = Bookings.query.filter_by(id=booking_id).one()

    try:
        if user.is_admin is True:
            update_booking.user_id = None
            update_booking.booking_type = "Lesson"
            update_booking.name = None
            db.session.commit()
            return render_template('session_confirm.html',
                                   session=update_booking)
        else:
            return render_template('session_confirm.html',
                                   session=update_booking)
    except:
        return render_template('date.html',
                               session=update_booking)


# FOR ADMIN LOG IN ONLY - Admin is able to clear the booking entry and user on any timeslot
# and remove lessons from the database and cancel players form the lessons


@main.route('/date/book/<int:booking_id>/delete', methods=["GET", "POST"])
@login_required
def booking_entry_delete(booking_id):
    user = current_user._get_current_object()
    update_booking = Bookings()
    update_booking = Bookings.query.filter_by(id=booking_id).one()

    try:
        if user.is_admin is True:
            update_booking.user_id = None
            update_booking.booking_type = None
            update_booking.name = None
            db.session.commit()
            return render_template('session_confirm.html', session=update_booking)
        else:
            return render_template('session_confirm.html', session=update_booking)
    except:
        return render_template('date.html', session=update_booking)

# Booking Routes

# User asked to select a date from drop down calender and function will
# population the date and present slots in the date page


@main.route('/query', methods=['GET'])
def query_date():

    try:
        entry = request.args.get('entry')
        bookings = Bookings.query.filter((Bookings.date) == entry).all()
        return render_template('date.html', bookings=bookings)
    except (Exception):
        return render_template('date.html')


# Users are able to book time slots on whatever date choosen

@main.route('/date/book/<int:booking_id>', methods=["GET", "POST"])
@login_required
def booking_entry_create(booking_id):

    try:

        update_booking = Bookings()
        user_id = current_user._get_current_object()
        name = current_user._get_current_object()
        valid = current_user._get_current_object()
        user = user_id.id
        name = name.name
        valid = valid.valid

        update_booking = Bookings.query.filter_by(id=booking_id).one()

        # checks to validate which user is logged in and their permissions
        # admin has above all privledge
        # valid users can book and edit but not edit other choosen ones
        # not valid users can not book anything

        if valid != "True":
            return render_template('date.html', session=update_booking, valid=valid)

        elif update_booking.user_id == None and current_user.is_admin == False and update_booking.booking_type == "Lesson":
            update_booking.user_id = user
            update_booking.name = name
            db.session.commit()
            
            return render_template('session_confirm.html', session=update_booking)

        elif update_booking.user_id == None and current_user.is_admin == False:
            update_booking.booking_type = "Casual"
            update_booking.user_id = user
            update_booking.name = name
            db.session.commit()
            return render_template('session_confirm.html', session=update_booking)

        elif update_booking.user_id == user:
            return render_template('session_confirm.html', session=update_booking)

        else:
            return render_template('date.html', session=update_booking)
    except:
        return render_template('date.html', session=update_booking)


# User cancels booking
@main.route('/date/book/<int:booking_id>/cancel', methods=["GET", "POST"])
@login_required
def booking_entry_update(booking_id):

    try:
        update_booking = Bookings()
        update_booking = Bookings.query.filter_by(id=booking_id).one()

        # checks to validate which user is logged in and their permissions
        # admin has above all privledge
        # valid users can book and edit but not edit other choosen ones
        # not valid users can not book anything

        if update_booking.user_id == current_user.id and update_booking.booking_type != "Lesson":

            update_booking.booking_type = None
            update_booking.user_id = None
            update_booking.name = None

            db.session.commit()
            return render_template('session_confirm.html', session=update_booking)

        elif update_booking.user_id == current_user.id and update_booking.booking_type == "Lesson":

            update_booking.user_id = None
            update_booking.name = None

            db.session.commit()
            return render_template('session_confirm.html', session=update_booking)

        elif current_user.is_admin == True and update_booking.booking_type == "Lesson":

            update_booking.user_id = None
            update_booking.name = None

            db.session.commit()
            return render_template('session_confirm.html', session=update_booking)

        elif current_user.is_admin == True and update_booking.booking_type != "Lesson":

            update_booking.user_id = None

src/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html>
<html id="background">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Murrumbeena Tennis Club</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<style>
  #nav_links:hover { color: #ff6600;
                     font-family: 'Orbitron', sans-serif;
                     font-weight: 100;
                     text-decoration: none;}

  #background {background-image: url("https://i.imgur.com/wzQbdNa.jpg") !important;}

  #nav_background {background-color: black !important;}

  #padding_section {padding-top: 70px;}

  #body_background {background-color: transparent;}

  #dropdown_background {background-color: white !important;}

  #dropdown_word_color {color: black;}
</style>

<body id="body_background">

    <section id="padding_section"></section>
        <div>
            <nav id="nav_background" class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="True" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  <div class="navbar-nav">
                    <a id="nav_links" class="nav-item nav-link" href="{{ url_for('main.index') }}">Home</a>
                    <a id="nav_links" class="nav-item nav-link" href="{{ url_for('main.play') }}">Want To Play</a>
                    <a id="nav_links" class="nav-item nav-link" href="{{ url_for('main.calendar') }}">Calendar</a>
                    <a id="nav_links" class="nav-item nav-link" href="{{ url_for('main.memberships') }}">Memberships</a>
                    <a id="nav_links" class="nav-item nav-link" href="{{ url_for('main.contact') }}">Contact</a>
                    <a id="nav_links" class="nav-item nav-link" href="{{ url_for('main.about') }}">About Us</a>
                    {% if current_user.is_authenticated %}
                    <div class="dropdown">
                      <a id="nav_links" class="nav-item nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Book A Session
                      </a>
                    
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{{ url_for('main.date') }}">Casual Play</a>
                        <a class="dropdown-item" href="{{ url_for('main.get_lessons') }}">Lessons</a>
                      </div>
                    </div>
                    {% endif %}
                    
                  </div>
                </div>

                <div style="justify-content: flex-end;" class="collapse navbar-collapse" id="navbarNavAltMarkup">
                  {% if current_user.is_anonymous %}
                    <a href="{{ url_for('auth.signup') }}"><button class="btn btn-outline-success" type="button" >Sign Up</button></a>
                    <a href="{{ url_for('auth.login') }}"><button class="btn btn-outline-success" type="button">Log In</button></a>
                  {% endif %}
                  {% if current_user.is_authenticated %}
                    <span class="btn btn-dark">{{ current_user.name }} </span>
                    {% if current_user.is_admin == True %}
                    <div class="dropdown">
                      <button class="btn btn-outline-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin
                      </button>
                      <div id="dropdown_background" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a id="dropdown_word_color" class="dropdown-item" href="{{ url_for('main.query_users') }}">Users</a>
                        <a id="dropdown_word_color" class="dropdown-item" href="{{ url_for('main.date') }}">Add Lessons</a>
                      </div>
                    </div>

                    {% endif %}
                    <a href="{{ url_for('main.profile') }}"><button class="btn btn-outline-success" type="button">Account</button></a>
                    <a href="{{ url_for('auth.logout') }}"><button class="btn btn-outline-success" type="button">Log Out</button></a>
                  {% endif %}
                </span>
              </nav>
        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {{ title }}
               {% endblock %}
            </div>
        </div>
    </section>
  

</body>
</html>

src/templates/date.html
{% extends "base.html" %}

{% block content %}



<form action="{{  url_for('main.query_date') }}"  method="GET">
  <label class="list-group-item list-group-item-dark" for="entry">Select the date to see all the sessions for the day:</label><br>
  <input style="font-size: 35px;" type="date" id="entry" name="entry">
  <br><br>
  <div class="buttons is-centered">
  <input class="btn btn-primary is-small box" class="button is-info is-small box has-text-centered" type="submit" value="Submit">
  </div>
</form>

<br><br>
{% for booking in bookings %}
<div class="box">
  <div class="columns has-text-left">
      <div class="column" style="text-align: center;">
        <p class="list-group-item list-group-item-dark" >Date:</p><br>
              {{ booking.date.strftime('%d-%m-%Y') }}
          </div>
          <div class="column" style="text-align: center;">
            <p class="list-group-item list-group-item-dark">Court:</p><br>
              {{ booking.court }}
        </div>
        <div class="column" style="text-align: center;">
          <p class="list-group-item list-group-item-dark">Time Slot:</p><br>
          {{ booking.time_slot }}
        </div>
        <div class="column" style="text-align: center;">
          <p class="list-group-item list-group-item-dark">Session Type:</p><br>
          {{ booking.booking_type }}
        </div>
        <div class="column" style="text-align: center;">
          <p class="list-group-item list-group-item-dark">Player:</p><br>
          {{ booking.name }}
        </div>

        <div><br>
        {% if current_user.valid == "True" and booking.user_id == None and current_user.is_admin != True %}
        <br>
        <a href="{{ url_for('main.booking_entry_create', booking_id=booking.id) }}" class="btn btn-primary is-small box" role="button" aria-pressed="true">Book</a>
        {% endif %}

        {% if booking.user_id == current_user.id and current_user.is_admin != True %}
        <br> 
        <a href="{{ url_for('main.booking_entry_create', booking_id=booking.id) }}" class="btn btn-success" class="btn btn-primary is-small box" role="button" aria-pressed="true">Edit</a>
        {% endif %}


        {% if current_user.is_admin == True %}
        <a href="{{ url_for('main.create_lessons', booking_id=booking.id) }}" class="btn btn-primary is-small box" role="button" aria-pressed="true">Lesson</a><div></div>
        <a href="{{ url_for('main.booking_entry_delete', booking_id=booking.id) }}" class="btn btn-primary is-small box" role="button" aria-pressed="true">Clear</a>
        {% endif %}
        </div>

  </div>
</div>
{% else %}
<br><br>
<div class="mgt-medium">
<div class="notification is-danger">
    <p>No entries recorded</p>
</div>
</div>
  {% endfor %}
















{% endblock %}

src/templates/lessons.html
{% extends "base.html" %}

{% block content %}



<h1 class="list-group-item list-group-item-dark" class="title">Lessons</h1>
{% for lesson in lessons %}
<div class="box">
  <div class="columns has-text-left">
      <div class="column" style="text-align: center;">
        <p class="list-group-item list-group-item-dark">Date:</p><br>
              {{ lesson.date.strftime('%d-%m-%Y') }}
          </div>
          <div class="column" style="text-align: center;">
            <p class="list-group-item list-group-item-dark">Court:</p><br>
              {{ lesson.court }}
        </div>
        <div class="column" style="text-align: center;">
          <p class="list-group-item list-group-item-dark">Time Slot:</p><br>
          {{ lesson.time_slot }}
        </div>
        <div class="column" style="text-align: center;">
          <p class="list-group-item list-group-item-dark">Session Type:</p><br>
          {{ lesson.booking_type }}
        </div>
        <div class="column" style="text-align: center;">
          <p class="list-group-item list-group-item-dark">Player:</p><br>
          {{ lesson.name }}
        </div>
        <div><br><br>
        {% if lesson.user_id == None and current_user.is_admin != True and current_user.valid != "false" %}
        <a href="{{ url_for('main.booking_entry_create', booking_id=lesson.id) }}" class="btn btn-primary is-small box" role="button" aria-pressed="true">Book</a>
        {% endif %}

        {% if lesson.user_id == current_user.id and current_user.is_admin != True %} 
        <a href="{{ url_for('main.create_lessons', booking_id=lesson.id) }}" class="btn btn-success" class="btn btn-primary is-small box" role="button" aria-pressed="true">Edit</a>
        {% endif %}

        {% if current_user.is_admin == True %}
        <a href="{{ url_for('main.create_lessons', booking_id=lesson.id) }}" class="btn btn-success" class="btn btn-primary is-small box" role="button" aria-pressed="true">Edit</a><div></div>
        {% endif %}
        </div>





  </div>
</div>
{% else %}
<br>
<div class="mgt-medium">
<div class="notification is-danger">
    <p>No entries recorded</p>
</div>
</div>
  {% endfor %}
















{% endblock %}

src/templates/profile.html
<!-- templates/profile.html -->

{% extends "base.html" %}

{% block content %}
<h1 class="list-group-item list-group-item-dark" class="title">{{ current_user.name }}</h1>

<div class="box">
  <div class="columns has-text-left">
    <div style="text-align: center;" class="column">

      <p class="list-group-item list-group-item-dark">Email:</p><br>
              {{ current_user.email }}
          </div>
          <div style="text-align: center;" class="column">

            <p class="list-group-item list-group-item-dark">Membership:</p><br>
              {{ current_user.membership }}
        </div>
        <div style="text-align: center;" class="column">

          <p class="list-group-item list-group-item-dark">Valid:</p><br>
          {{ current_user.valid }}
        </div>
        <div style="text-align: center;" class="column">

          <p class="list-group-item list-group-item-dark">Valid Till:</p><br>
          {{ current_user.valid_till }}
        </div>
  </div>
</div> 

{% if current_user.is_admin != True %}
<div class="card mb-3">
  <img src="https://i.imgur.com/aVTxTxE.jpg" class="card-img-top" alt="..."></div>
  <div class="card-body">
  <h5 class="list-group-item list-group-item-dark" class="card-title">Sessions</h5></div>
  {% for session in sessions %}
  
  <div class="box">
    <div class="columns has-text-left">
        <div style="text-align: center;" class="column">

          <p class="list-group-item list-group-item-dark">Date:</p><br>
                {{ session.date.strftime('%d-%m-%Y') }}
            </div>
            <div style="text-align: center;" class="column">
              <p class="list-group-item list-group-item-dark">Court:</p><br>
                {{ session.court }}
          </div>
          <div style="text-align: center;" class="column">
            <p class="list-group-item list-group-item-dark">Booking Type:</p><br>
              {{ session.booking_type }}
        </div>
          <div style="text-align: center;" class="column">
            <p class="list-group-item list-group-item-dark">Time Slot:</p><br>
            {{ session.time_slot }}
          </div><div><br><br>
            <a class="btn btn-danger" class="btn btn-primary is-small box" role="button" aria-pressed="true" href="{{ url_for('main.booking_entry_update', booking_id=session.id) }}" >Cancel</a></div>
      </div>
    </div>
{% endfor %}
{% endif %}

  {% if current_user.is_admin == True %}
    <div class="card-body">
    <h5 class="list-group-item list-group-item-dark" class="card-title">Lessons</h5></div>
    {% for lesson in lessons %}
  
    <div class="box">
      <div class="columns has-text-left">
          <div class="column" style="text-align: center;">
            <p class="list-group-item list-group-item-dark">Date:</p><br>
                  {{ lesson.date }}
              </div>
              <div class="column" style="text-align: center;">
                <p class="list-group-item list-group-item-dark">Court:</p><br>
                  {{ lesson.court }}
            </div>
            <div class="column" style="text-align: center;">
              <p class="list-group-item list-group-item-dark">Time Slot:</p><br>
              {{ lesson.time_slot }}
            </div>
            <div class="column" style="text-align: center;">
              <p class="list-group-item list-group-item-dark">Player:</p><br>
              {{ lesson.name }}
            </div><div><br><br>
            <a class="btn btn-danger" class="btn btn-primary is-small box" role="button" aria-pressed="true" href="{{ url_for('main.booking_entry_update', booking_id=lesson.id) }}" >Cancel</a></div>
      </div>
    </div>

{% endfor %}
{% endif %}



  <div class="column is-4 is-offset-4">
    <h3 class="list-group-item list-group-item-dark" class="title">Change Password</h3>
    <div class="box">
        {% if error %}<p class=error><strong>Error:</strong> {{ error }}{% endif %}
          {% with messages = get_flashed_messages() %}
          {% if messages %}
              <div class="notification is-danger">
                  {{ messages[0] }}
              </div>
          {% endif %}
          {% endwith %}
        <form action="{{ url_for('auth.user_password_change') }}"  method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="New Password">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Change</button>
        </form>
    </div>
</div>
{% endblock %} 

src/templates/session_confirm.html
{% extends "base.html" %}

{% block content %}

{% if session.name != "None" %}
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Success!</h4>
  <p>Your Booking has been confirmed</p>
  <hr>
</div>
{% endif %}
{% if session.name == "None" %}
<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">Success!</h4>
  <p>Your Booking has been cancelled</p>
  <hr>
</div>
{% endif %}

<br>

<div class="box">
  <div class="columns has-text-left">
      <div style="text-align: center;" class="column">
        <p class="list-group-item list-group-item-dark" >Date:</p><br>
              {{ session.date.strftime('%d-%m-%Y') }}
          </div>
          <div style="text-align: center;" class="column">
            <p class="list-group-item list-group-item-dark" >Court:</p><br>
              {{ session.court }}
        </div>
        <div style="text-align: center;" class="column">
          <p class="list-group-item list-group-item-dark" >Time Slot:</p><br>
          {{ session.time_slot }}
        </div>
        <div style="text-align: center;"class="column">
          <p class="list-group-item list-group-item-dark" >Session Type:</p><br>
          {{ session.booking_type }}
        </div>
        <div style="text-align: center;" class="column">
          <p class="list-group-item list-group-item-dark" >Player:</p><br>
            {{ session.name }}
        </div>
  </div>
</div>


<a class="btn btn btn-primary" href="{{ url_for('main.date') }}" role="button">Calendar</a>
{% if current_user.is_admin == False %}
<a class="btn btn btn-primary" href="{{ url_for('main.booking_entry_update', booking_id=session.id) }}" role="button">Cancel</a>
{% endif %}
{% if current_user.is_admin == True %}
<a class="btn btn btn-primary" href="{{ url_for('main.booking_entry_delete', booking_id=session.id) }}" role="button">Delete</a>
{% endif %}



{% endblock %}